//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_User
    {
        //public All_User()
        //{
        //    this.Permissions = new HashSet<Permission>();
        //}
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        //public virtual ICollection<Permission> Permissions { get; set; }
    }
}
