//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationUser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClsPrac2Entities_Context : DbContext
    {
        public ClsPrac2Entities_Context()
            : base("name=ClsPrac2Entities_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<All_User> All_User { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Roll> Rolls { get; set; }
    }
}
