//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int P_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> R_Id { get; set; }
    
        public virtual All_User All_User { get; set; }
        public virtual Roll Roll { get; set; }
    }
}
